### ISSUE TITLE
Some comments on Notebook

### ISSUE THREAD

**Issue by matsuot-cu** [AMGeO-Collaboration/Earthcube-Meeting-2021#1]
### AMGeO

**Original**
_"AMGeO is a data science software project funded by the NSF EarthCube programaiming to open up the vast amount of geospace data to a broader audience, while also giving users an access to data analysis tools that help gain meaningful insights from this data"_  
**New**
"AMGeO is a data science tool for the geospace community that combines observations from various sensors into assimilative maps of the high-latitude ionosphere. With the support from the NSF EarthCube program, AMGeO is set out to open up the large amount of information-rich geospace data to a broader audience, while also giving users an access to data analysis tools that help gain meaningful insights from a collection of geospace data." 

### Purpose

**Original**
_"To empower new and existing users of AMGeO in pursuit of their research goals, a new API (Application Programming Interface) is being developed. It will offer a smoother introduction for new users to the tools provided by AMGeO, and also facilitate efficient workflows for experienced users."_
**New**
"To empower new and existing users of AMGeO in pursuit of their research goals, a new API (Application Programming Interface) is being developed. It is intended to offer a smoother introduction for new users to the tools provided by AMGeO and facilitate efficient workflows for experienced users. While AMGeO is highly customizable and offers researchers an array of tools to transform raw geospace data into discovery enabling forms, some additional post processing may be desirable to further manipulate AMGeO data products to meet users' unique needs.  This notebook, as a showcase of the new API, is intended to further facilitate the ease of use with AMGeO for users with different levels of experience."

### Technical contributions
**Original** (Purpose)
_"This notebook showcases the new API, and example use cases given differnent levels of experience/tasks to complete._
**New**
"This notebook showcases and provides example use cases for the new API in three levels of experience settings."

### Methodology
**Original** 
_"During the development of the new API, our main target audience has been users who may not have a lot of experience with python, or don't want to have to manually read data from hdf5 files. To make this process easier for such users, tools like xarray and numpy are being used to help new users get off the ground running."_
**New**
"To meet the needs of target audience with little python experience and no desire to manually read data from AMGeO data product files in hdf5 format, tools like xarray and numpy are being used to help novice users get off the ground running. For users with more experience, a number of configuration tools are also being provided to support their wish to tailor post processing steps to their specific needs."

### Results
**Original** 
_"The new AMGeO API is currently still in testing, but we currently have a demo (this notebook) and a future workshop to showcase this new tool. Once fully tested, the new API will be available to all users of AMGeO."_
**New**
"The new API is being designed and developed with the intention of facilitating the ease of use with AMGeO. This notebook  helps users with different levels of experience to work through example use cases of using the API."

### Funding 
**Original**
_"TODO: NSF Grant here"_
**New**
"AMGeO is supported by the NSF EarthCube grants ICER 1928403 to the University of Colorado Boulder, ICER 1928327 to the Virginia Tech, and ICER 1928358 to the Johns Hopkins University Applied Physics Laboratory. 

### Citation
AMGeO Collaboration (2019), A Collaborative Data Science Platform for the Geospace Community: Assimilative Mapping of Geospace Observations (AMGeO) v1.0.0, http://doi.org/10.5281/zenodo.3564914.

### Suggested next steps
To learn more about AMGeO and get a hands-on experience with the API presented here, please join us at our virtual  tutorial and interactive demos at 1-3pm MDT on June 25 (Friday) 2021. For more information, see http://cedarweb.vsp.ucar.edu/wiki/index.php/2021_Workshop:AMGeO.

### Acknowledgements 
We are grateful for the community data providers (NASA SPDF, SuperMAG, SuperDARN, AMPERE) for providing data for the community such that they can be used in AMGeO. The use of the AMGeO software with the SuperMAG data requires you to use its individual SuperMAG account to access the SuperMAG data service. It is your responsibility to follow
the terms and conditions and the acknowledgement and citation requirements of the
SuperMAG found at http://supermag.jhuapl.edu. The use of the AMGeO software with the SuperDARN data requires you to follow the terms and conditions and the acknowledgement and citation requirements of the SuperDARN
found at http://vt.superdarn.org/tiki-index.php.  The use of the AMGeO software with the AMPERE data requires you to follow the terms and conditions and the acknowledgement and citation requirements of the AMPERE
found at http://ampere.jhuapl.edu.

**Comment by willemmirkovich** [comment]
Thanks for this Tomoko, have made most of the edits but still have some questions we can go over later today

**Comment by willemmirkovich** [comment]
Resolved with latest changes
